name: syn-iss-seg
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch>=2.0
  - torchvision>=0.15
  - cudatoolkit=11.8
  - segmentation-models-pytorch=0.3.3
  - albumentations>=1.3.0
  - opencv-python>=4.8.0
  - numpy>=1.23.5
  - pandas>=1.5.3
  - matplotlib>=3.7.0
  - scikit-learn>=1.3.0
  - tqdm>=4.65.0
  - pillow>=9.5.0
  - jupyterlab>=4.0.0
  - notebook>=7.0.0
